import image1 from "../img/shofk-1.jpg";
import image2 from "../img/shofk-2.jpg";
import image3 from "../img/shofk-3.jpg";
import image4 from "../img/shofk-4.jpg";
import image5 from "../img/shofk-5.jpg";
import image6 from "../img/shofk-6.jpg";
import image7 from "../img/shofk-7.jpg";
import image8 from "../img/shofk-8.jpg";
import image9 from "../img/shofk-9.jpg";
import image10 from "../img/shofk-10.jpg";
import image11 from "../img/shofk-11.jpg";
import image12 from "../img/shofk-12.jpg";
import image13 from "../img/shofk-13.jpg";
import image14 from "../img/shofk-14.jpg";
import image15 from "../img/shofk-15.jpg";
import image16 from "../img/shofk-16.jpg";
import image17 from "../img/shofk-17.jpg";
import image18 from "../img/shofk-18.jpg";
import image19 from "../img/shofk-19.jpg";
import image20 from "../img/shofk-20.jpg";
import image21 from "../img/shofk-21.jpg"; 
import image22 from "../img/shofk-22.jpg"; 
import image23 from "../img/shofk-23.jpg"; 
import image24 from "../img/shofk-24.jpg"; 
import image25 from "../img/shofk-25.jpg"; 
import image26 from "../img/shofk-26.jpg"; 
import image27 from "../img/shofk-27.jpg"; 
import image28 from "../img/shofk-28.jpg"; 

const galeryData = [
    { image: image1 },
    { image: image2 },
    { image: image28 }, 
    { image: image3 },
    { image: image4 },
    { image: image5 },
    { image: image6 },
    { image: image7 },
    { image: image8 },
    { image: image9 },
    { image: image10 },
    { image: image11 },
    { image: image12 },
    { image: image13 },
    { image: image14 },
    { image: image15 },
    { image: image16 },
    { image: image17 },
    { image: image18 },
    { image: image19 },
    { image: image20 },
    { image: image21 }, 
    { image: image22 }, 
    { image: image23 }, 
    { image: image24 },
    { image: image25 }, 
    { image: image26 }, 
    { image: image27 },
];

export { galeryData };
